# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15cfd459daa6620338d93f453e273e43976429d5247773e08b1b7064b4ac3b0923e798833499abe56fa199f7957af206b3b84cfe27086f1ecd2ae57e2458d224

test:
  secret_key_base: d8a5f77aa0bb194e5f75755b68fc8c32c741cda2e8a1945ff22f1317755015bacf6ca6b0d93443cb4d9fff10370b0f400bc06946dd85a26f470e8c21af75fbd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
